version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:6
    container_name: gdpr-audit-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: gdpr-education-audit
    volumes:
      - mongodb_data:/data/db
    networks:
      - gdpr-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: gdpr-audit-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - gdpr-network

  # Elasticsearch for logging (optional)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: gdpr-audit-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - gdpr-network

  # Kibana for log visualization (optional)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: gdpr-audit-kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - gdpr-network

  # Node.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gdpr-audit-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/gdpr-education-audit?authSource=admin
      REDIS_URL: redis://redis:6379
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./credentials:/app/credentials:ro
    depends_on:
      - mongodb
      - redis
    networks:
      - gdpr-network

volumes:
  mongodb_data:
  redis_data:
  elastic_data:

networks:
  gdpr-network:
    driver: bridge
